name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: install deps
      run: npm ci

    - name: Fetch latest data
      run: |-
        price=$(xvfb-run node scrape.js | tee price.txt)
        if [[ ! $price =~ ^\$[0-9.]+$ ]];
        then
          echo "Did not retrieve a valid price! - $price"
          exit 1
        fi

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest price: $(cat price.txt)" || exit 0
        git push