name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          **/node_modules
        key: ${{ hashFiles('package-lock.json') }}

    - name: install deps
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci

    - name: Fetch latest data
      run: |-
        xvfb-run node scrape.js | tee price.txt

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest price: $(cat price.txt)" || exit 0
        git push